field.widget.settings.select_or_other_reference:
  type: mapping
  label: 'Select or other reference widget display format settings'
  mapping:
    select_element_type:
      type: string
      label: 'Type of select form element'
